### ISSUE TITLE
Error when starting bot

### ISSUE THREAD

**Issue by a0v0** [Sam-Max/rclone-mirror-leech-telegram-bot#107]
```
Recreating rcmltb ... done
Attaching to rcmltb
rcmltb | 2023-02-26 11:29:34,052 - root - INFO - Successfully updated from UPSTREAM_REPO
rcmltb | 2023-02-26 11:29:37,678 INFO MainThread bot Creating Pyrogram client
rcmltb | QtSingleCoreApplication: listen on local socket failed, QLocalServer::listen: Name error
rcmltb | [2023-02-26 11:29:38 +0000] [39] [INFO] Starting gunicorn 20.1.0
rcmltb | [2023-02-26 11:29:38 +0000] [40] [INFO] Starting gunicorn 20.1.0
rcmltb | [2023-02-26 11:29:38 +0000] [39] [INFO] Listening at: http://0.0.0.0:81 (39)
rcmltb | [2023-02-26 11:29:38 +0000] [40] [INFO] Listening at: http://0.0.0.0:80 (40)
rcmltb | [2023-02-26 11:29:38 +0000] [39] [INFO] Using worker: sync
rcmltb | [2023-02-26 11:29:38 +0000] [40] [INFO] Using worker: sync
rcmltb | [2023-02-26 11:29:38 +0000] [67] [INFO] Booting worker with pid: 67
rcmltb | [2023-02-26 11:29:38 +0000] [68] [INFO] Booting worker with pid: 68
rcmltb | caution: filename not matched:  -w
rcmltb | 2023-02-26 11:29:38,830 INFO Thread-1 (aria2c_init) bot Initializing Aria2c
rcmltb | Traceback (most recent call last):
rcmltb |   File "<frozen runpy>", line 198, in _run_module_as_main
rcmltb |   File "<frozen runpy>", line 88, in _run_code
rcmltb |   File "/usr/src/app/bot/__main__.py", line 15, in <module>
rcmltb |     from .helper.ext_utils import db_handler
rcmltb |   File "/usr/src/app/bot/helper/ext_utils/db_handler.py", line 128, in <module>
rcmltb |     botloop.run_until_complete(DbManager().db_load())
rcmltb |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
rcmltb |   File "/usr/src/app/bot/helper/ext_utils/db_handler.py", line 50, in db_load
rcmltb |     if await self.__db.rss[bot_id].find_one():
rcmltb |              ~~~~~~~~~~~~~^^^^^^^^
rcmltb |   File "/usr/lib/python3.11/site-packages/motor/core.py", line 853, in __getitem__
rcmltb |     self.database, self.name + "." + name, _delegate=self.delegate[name]
rcmltb |                    ~~~~~~~~~~~~~~~~^~~~~~
rcmltb | TypeError: can only concatenate str (not "int") to str

```

**Comment by khainee** [comment]
I solved it on https://github.com/khainee/rclone-mirror-leech-telegram-bot-1/tree/patch-1

**Comment by Sam-Max** [comment]
Fixed
