### ISSUE TITLE
Can't upload videos over 2GB

### ISSUE THREAD

**Issue by tuthanika** [Sam-Max/rclone-mirror-leech-telegram-bot#132]
Videos over 2GB don't automatically split, split option is enabled in bot configuration.

2023-04-07 04:03:46,581 ERROR MainThread pyrogram.dispatcher Can't upload files bigger than 2000 MiB
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
await handler.callback(self.client, *args)
File "/usr/src/app/bot/modules/leech.py", line 183, in selection_callback
await mirror_leech(client, message, isZip=is_zip, extract=extract, isLeech=True)
File "/usr/src/app/bot/modules/mirror_leech.py", line 228, in mirror_leech
await add_gd_download(link, f'{DOWNLOAD_DIR}{listener.uid}', listener, name)
File "/usr/src/app/bot/helper/mirror_leech_utils/download_utils/gd_downloader.py", line 22, in add_gd_download
await drive.download(link)
File "/usr/src/app/bot/helper/mirror_leech_utils/upload_utils/gdriveTools.py", line 332, in download
await self.__listener.onDownloadComplete()
File "/usr/src/app/bot/modules/listener.py", line 238, in onDownloadComplete
await tg_up.upload()
File "/usr/src/app/bot/helper/mirror_leech_utils/upload_utils/telegram_uploader.py", line 52, in upload
await self.__upload_file(f_path, file)
File "/usr/src/app/bot/helper/mirror_leech_utils/upload_utils/telegram_uploader.py", line 221, in __upload_file
raise err
File "/usr/src/app/bot/helper/mirror_leech_utils/upload_utils/telegram_uploader.py", line 145, in __upload_file
self.__sent_msg= await self.__sent_msg.reply_video(
File "/usr/local/lib/python3.8/dist-packages/pyrogram/types/messages_and_media/message.py", line 2494, in reply_video
return await self._client.send_video(
File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_video.py", line 187, in send_video
file = await self.save_file(video, progress=progress, progress_args=progress_args)
File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/save_file.py", line 134, in save_file
raise ValueError(f"Can't upload files bigger than {file_size_limit_mib} MiB")
ValueError: Can't upload files bigger than 2000 MiB

**Comment by Sam-Max** [comment]
It is fixed now
