### ISSUE TITLE
Still giving error for multiple tasks

### ISSUE THREAD

**Issue by Sledger9** [Sam-Max/rclone-mirror-leech-telegram-bot#143]
2023-05-22 10:17:43,822 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4233' coro=<setInterval.setInterval() done, defined at /usr/src/app/bot/helper/ext_utils/bot_utils.py:219> exception=AttributeError("'MirrorLeechListener' object has no attribute 'newDir'")>
Traceback (most recent call last):
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 222, in setInterval
    await self.action()
  File "/usr/src/app/bot/helper/telegram_helper/message_utils.py", line 126, in update_all_messages
    msg, buttons = await get_readable_message()
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 141, in get_readable_message
    msg += f"\n<b>Processed:</b> {download.processed_bytes()} of {download.size()}"
  File "/usr/src/app/bot/helper/mirror_leech_utils/status_utils/zip_status.py", line 58, in processed_bytes
    return get_readable_file_size(self.processed_raw())
  File "/usr/src/app/bot/helper/mirror_leech_utils/status_utils/zip_status.py", line 52, in processed_raw
    if self.__listener.newDir:
AttributeError: 'MirrorLeechListener' object has no attribute 'newDir'

**Comment by Sam-Max** [comment]
Fixed now, test
