### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by pachax001** [Sam-Max/rclone-mirror-leech-telegram-bot#51]
After new commit bot upload not working.I am trying to upload to my onedrive.But the download progress is stuck at 100% and upload is not working.
2022-10-15 15:39:43,645 INFO Thread-4 (__onDownloadStarted) bot onDownloadStarted: goong.s1.br.48-pahe.ph.part1.rar - Gid: 5fa90b7664d64445
2022-10-15 15:39:43,646 INFO MainThread bot Aria2Download started: 5fa90b7664d64445
2022-10-15 15:40:28,639 INFO Thread-5 (__onDownloadComplete) bot onDownloadComplete: goong.s1.br.48-pahe.ph.part1.rar - Gid: 5fa90b7664d64445
2022-10-15 15:40:33,824 ERROR MainThread asyncio Task exception was never retrieved
future: <Task finished name='Task-3210' coro=<setInterval.setInterval() done, defined at /usr/src/app/bot/helper/ext_utils/bot_utils.py:176> exception=RuntimeError('<asyncio.locks.Lock object at 0xffff8d5adc30 [unlocked, waiters:1]> is bound to a different event loop')>
Traceback (most recent call last):
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 181, in setInterval
    await self.action()
  File "/usr/src/app/bot/helper/ext_utils/message_utils.py", line 119, in update_all_messages
    msg, buttons = await get_readable_message()
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 96, in get_readable_message
    async with status_dict_lock:
  File "/usr/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.10/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
  File "/usr/lib/python3.10/asyncio/mixins.py", line 30, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0xffff8d5adc30 [unlocked, waiters:1]> is bound to a different event loop
2022-10-15 15:47:26,393 INFO MainThread pyrogram.connection.connection Connecting...
2022-10-15 15:47:26,450 INFO MainThread pyrogram.connection.connection Connected! Production DC5 (media) - IPv4 - TCPAbridgedO
2022-10-15 15:47:26,451 INFO MainThread pyrogram.session.session NetworkTask started
2022-10-15 15:47:26,753 INFO MainThread pyrogram.session.session Session initialized: Layer 146
2022-10-15 15:47:26,753 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.57
2022-10-15 15:47:26,753 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1019-oracle (EN)
2022-10-15 15:47:26,753 INFO MainThread pyrogram.session.session Session started

**Comment by rinrinx** [comment]
No bro good work delete old repo, git clone new repo try

**Comment by pachax001** [comment]
> No bro good work delete old repo, git clone new repo try

Tried it.same happens

**Comment by rinrinx** [comment]
> > No bro good work delete old repo, git clone new repo try
> 
> Tried it.same happens

No bro work i test bot now
