### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by theseeker99** [Sam-Max/rclone-mirror-leech-telegram-bot#71]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 84, in <module>
    with open(file_, 'wb+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/users/1499473343/rclone.conf'
2022-12-13 16:56:04,251 ERROR MainThread asyncio Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff4ee789960>

**Comment by nnhieu97** [comment]
bro how can you fix this?
